version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db_sea_level
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80" # You can access phpMyAdmin from localhost:8080
      environment:
        PMA_HOST: mysql # This should match the name of your MySQL service defined above
        MYSQL_ROOT_PASSWORD: root_password # Same password as MySQL root password